#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/scss-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/bootstrap/**/*.*'
preprocess_command: "gsed '1{/^---$/{:a N;/---$/!ba;d}}'"
