# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anton Tetov
description: portfolio for architecture student

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tetov.se" # the base hostname & protocol for your site, e.g. http://example.com
assets-url: "https://tetov-assets.nyc3.digitaloceanspaces.com"

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"

author:
    name: Anton Tetov
    twitter: te_tov

blog_url: "https://blog.tetov.se/"
email: anton@tetov.se
twitter_username: te_tov
github_username: tetov
tumblr_username: tetov
instagram_username: antontetov
pgpkey_url: "pgpkey"

google_site_verification: Uz3ipYQgkud5NHu9JC-t-AjF2N3lI5eXDKJ0XsuIgXc

permalink: /:title/

# Build settings
markdown: kramdown
plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
exclude:
    - build.sh
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - node_modules
    - package-lock.json
    - package.json
    - README.md
    - vendor/bundle
# Compress settings
compress_html:
    comments: ["<!-- ", " -->"]
    blanklines: false
