# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anton Tetov Portfolio
email: anton@tetov.se
description: portfolio for architecture student
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tetov.se" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: tetov2
author:
  twitter: tetov2

github_username: tetov
tumblr_username: tetov
pgpkey_url: "pgpkey"

logo:

social:
  links:
    - https://twitter.com/tetov2
    - https://www.facebook.com/ntntvjhnssn
    - https://github.com/tetov
    - https://keybase.io/sonyamamurin

google_site_verification: Uz3ipYQgkud5NHu9JC-t-AjF2N3lI5eXDKJ0XsuIgXc

navigation:
- about
- log

permalink: /:categories/:title.html

# Build settings
sass:
    sass_dir: _sass
    style: compressed
markdown: kramdown
gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jemoji
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package.json
    - .scss-lint.yml
# Compress settings
compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: false
