# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anton Tetov
description: portfolio for architecture student

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tetov.se" # the base hostname & protocol for your site, e.g. http://example.com
assets-url: "https://assets.tetov.se"

logo: /logo.svg

author:
    twitter: tetov2

email: anton@tetov.se
twitter_username: tetov2
github_username: tetov
tumblr_username: tetov
pgpkey_url: "pgpkey"

social:
  links:
    - https://twitter.com/tetov2
    - https://www.facebook.com/ntntvjhnssn
    - https://github.com/tetov

google_site_verification: Uz3ipYQgkud5NHu9JC-t-AjF2N3lI5eXDKJ0XsuIgXc

navigation:
    - about
    - log

permalink: /:title/

# Build settings
sass:
    sass_dir: _sass
    style: compressed
markdown: kramdown
gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - gulpfile.js
    - package-lock.json
    - package.json
    - README.md
    - .scss-lint.yml
# Compress settings
compress_html:
    comments: ["<!-- ", " -->"]
    blanklines: false
